static const UnicodeString BadFiles[] = {
    "autorun.inf",
    "New Folder.exe",
    "newfolder.exe",
    "New_Folder.exe",
    "Explorer.exe",
    "autorun.vbs",
    "autorun.bat",
    "autorun.exe",
    "scene.exe",
    "AdobeRd9.0.exe",
    "System32.sys.vbs",
    "NTDETECT.exe",
    "boot.exe",
    "boot.vbs",
    "True Love.exe",
    "True_Love.exe",
    "killvbs.vbs",
    "system3_.exe",
    "a63grox.exe",
    "10nb.exe",
    "herss.exe",
    "open.exe",
    "smss.exe",
    "winfile.exe",
    "run.wsh",
    "SCVVHSOT.exe",
    "SCVHOST.exe",
    "kinza.exe",
    "sxs.exe",
    "stnetlib.exe",
    "diskdrive.exe",
    "Recycled.exe",
    "DESKTOP_.INI",
    "spoclsv.exe",
    "`.vbs",
    "`.vbe",
    "Picture.exe",
    "regsvr.exe",
    "copy.exe", "host.exe",
    "tel.xls.exe", "mmc.exe",
    "Fucker.vbs",
    "soundmix.exe",
    "RVHost.exe",
    "Macromedia__Setup.exe",
    "destrukto.vbs",
    "yahoomail.exe",
    "pendrive.exe",
    "wscript.exe",
    "uqSkRW.exe",
    "FAantivirus.vbs",
    NULL
  };
